version: '3.8'

services:
  clickhouse-server-1:
    image: clickhouse/clickhouse-server:25.2
    container_name: clickhouse-server-1
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    environment:
      - CLICKHOUSE_DB=imdb
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=12345
    volumes:
      - data_1:/var/lib/clickhouse
      - ./imdb:/var/lib/clickhouse/user_files
    networks:
      - clickhouse_network

  clickhouse-server-2:
    image: clickhouse/clickhouse-server:25.2
    container_name: clickhouse-server-2
    ports:
      - "8124:8123"
      - "9001:9000"
      - "9010:9009"
    environment:
      - CLICKHOUSE_DB=imdb
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=12345
    volumes:
      - data_2:/var/lib/clickhouse
    networks:
      - clickhouse_network

volumes:
  data_1:
  data_2:

networks:
  clickhouse_network:
    driver: bridge
